aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: us-east-1
  dynamodb:
    table-name: Franchises
microservice:
  exception:
    perzonalizada: Se generó un error del negocio
    system: Se generó un error del sistema